module.exports = {
  Accumulator: require('./accumulator/accumulator'),
  Bag: require('./bag/bag'),
  BinarySearch: require('./binary-search/binary-search'),
  BinarySearchRecursive: require('./binary-search/binary-search-recursive'),
  Counter: require('./counter/counter'),
  DateBasic: require('./date/date-basic'),
  DateSmall: require('./date/date-small'),
  DijkstraTwoStack: require('./dijkstra/dijkstra-two-stack'),
  Euclidean: require('./euclidean/euclidean'),
  LinearSearch: require('./linear-search/linear-search'),
  Queue: require('./queue/queue'),
  Stack: require('./stack/stack'),
  StackFixedCapacity: require('./stack/stack-fixed-capacity'),
  StackResizableArray: require('./stack/stack-resizable-array'),
  StopWatch: require('./stop-watch/stop-watch'),
  ThreeSum: require('./three-sum/three-sum'),
  ThreeSumFast: require('./three-sum/three-sum-fast'),
  Transaction: require('./transaction/transaction'),
  TwoSumFast: require('./two-sum/two-sum-fast'),
  UnionFind: require('./union-find/union-find'),
  UnionFindQuick: require('./union-find/union-find-quick')
}
